# Generated by Django 6.1.1 on 2026-10-01 11:30

from django.db import migrations, models


def copy_legacy_fixed_voucher_values(apps, schema_editor):
    GiftVoucher = apps.get_model('orders', 'GiftVoucher')
    GiftVoucher.objects.using(schema_editor.connection.alias).update(
        discount_value=models.F('initial_balance'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_giftvoucher_order_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvoucher',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='maximum_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(copy_legacy_fixed_voucher_values, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='giftvoucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'fixed'), ('discount_value__gte', 0)), models.Q(('discount_type', 'percentage'), ('discount_value__gt', 0), ('discount_value__lte', 100), ('initial_balance', 0), ('remaining_balance', 0)), _connector='OR'), name='valid_gift_voucher_discount_type_value'),
        ),
        migrations.AddConstraint(
            model_name='giftvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_discount_amount__isnull', True), ('maximum_discount_amount__gte', 0), _connector='OR'), name='nonnegative_gift_voucher_max_discount'),
        ),
    ]
